use_frameworks!

platform :ios, '8.0'

target 'PPSPublicStaticLibrary_Example' do
  pod 'PPSPublicStaticLibrary', :path => '../'

  target 'PPSPublicStaticLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
